[Iris]
AppName = "dengzi's blog"
Owner = "dengzi"
Port    = 8000
Charset = "UTF-8"

[db]
Host     = ""
Port     = 3306
Database = "blog_dev"
Username = ""
Password = ""
Charset  = "utf8"
LogEnable = true