[Iris]
AppName = "dengzi's blog"
Owner = "dengzi"
Port    = 8000
Charset = "UTF-8"

[db]
Host     = "dengzii.com"
Port     = 3306
Database = "blog_dev"
Username = "dengzi"
Password = "djh1713."
Charset  = "utf8"
LogEnable = true